import React from 'react';

export const Sample = () => (
  <div id="sample-wrapper">
    {/* <!-- 15 x 15 block --> */}
    {/* <!-- first row --> */}
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    {/* <!-- second row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- third row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- fourth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- fifth row --> */}
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- sixth row --> */}
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    {/* <!-- seventh row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    {/* <!-- eighth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- ninth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- tenth row --> */}
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- eleventh row --> */}
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    <div class="filled"></div>
    {/* <!-- twelfth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    <div class="empty numbered"></div>
    {/* <!-- thirteenth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- fourteenth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    {/* <!-- fifteenth row --> */}
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="filled"></div>
    <div class="empty numbered"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
  </div>
);
